### ISSUE TITLE
Remove V8 from Apollo Router

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/federation-next#22]
**This ticket has been moved to https://apollographql.atlassian.net/browse/FED-96.**

---

Before this can happen, various pieces of functionality currently provided by [router-bridge](https://github.com/apollographql/federation-rs/tree/main/federation-2/router-bridge) need to have a Rust replacement:

```
### Tasks
- [ ] https://github.com/apollographql/federation-planning/issues/458
- [ ] https://github.com/apollographql/federation-planning/issues/385
- [ ] https://github.com/apollographql/federation-next/issues/26
- [ ] https://github.com/apollographql/federation-planning/issues/384
- [ ] https://github.com/apollographql/federation-next/issues/31
```
