### ISSUE TITLE
epic: testing - planning

### ISSUE THREAD

**Issue by jeffjakub** [apollographql/federation-next#24]
As an engineer, I would like to:
- set up unit, integration tests, performance tests

So that we have quality metrics established at the start of the project to establish a baseline.

Acceptance Criteria
- [x]  unit tests and integration tests should be written as part of standard development
- [ ] migrating existing jest tests, should be done as part of development process
- [ ] performance test (query-planner) (get a random sample from test harness, establish a baseline) (M)
- [ ] performance tests (router) (@jeff to follow up w/ Polaris team)
- [ ] harness tests (we need to revisit the test harness retro tasks) (M)
- [ ] additional integration test for wasm support (needed for Studio where fetch plan is visually represented) (@jeff to follow up w/ Pulsar team)
- [ ] backwards compatibility tests - runs fed2x and fed-next, compares output to validate equivalence. (tool, take dataset from perf tests, CI) (M)
- [ ] setup test fuzzing for unit testing (S)

**Comment by dariuszkuc** [comment]
We have a pretty good testing strategy figured out. Closing this in favor of more specific items.
